AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image object identifier

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events: 
        FetchObjects:
          Type: Api
          Properties:
            Path: /fetchObjects
            Method: post